# Generated by Django 5.1.3 on 2024-12-10 11:54

import django.db.models.deletion
import django.utils.timezone
import passport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=passport.models.default_expiry_date)),
                ('membership_tier', models.CharField(choices=[('BASIC', 'Basic'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BASIC', max_length=10)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='users.profile')),
            ],
        ),
    ]
